### ISSUE TITLE
Can you specify the licency under which this is distributed ?

### ISSUE THREAD

**Issue by trivedip** [angelaHillier/Kinect-Studio-Sample#1]
I am a graduate student and would like to utilize this code. Can I use the code (I will give full credit to the author and Microsoft for the hardware and software.)

**Comment by angelaHillier** [comment]
Yes, we released this as open source to encourage people to customize/adapt Kinect Studio to their own needs. Please give credit to Microsoft, as more than just myself worked on the project (we were all paid by Microsoft to write the code).Good luck in your graduate work!~Angela


On ‎Wednesday‎, ‎August‎ ‎9‎, ‎2017‎ ‎10‎:‎15‎:‎42‎ ‎AM‎ ‎PDT, trivedip <notifications@github.com> wrote:


I am a graduate student and would like to utilize this code. Can I use the code (I will give full credit to the author and Microsoft for the hardware and software.)

**Comment by trivedip** [comment]
Also had a query, the code is very well written, but have very bad documentation. If I add documentation will you be willing to push to the main branch? 
It will be a great help to other people like me!
